# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np
arr = np.random.uniform(0, 21, size = (4, 7)).round(3)
min_val = arr.min()
max_val = arr.max()
x = arr
a = 1/(max_val-min_val)
b = -a*min_val
ans = a * x + b
ans

array([[0.23930836, 0.96766571, 0.87769452, 0.6674928 , 0.37752161,
        0.61792507, 0.        ],
       [0.85919308, 0.74801153, 0.58213256, 0.36507205, 0.0410951 ,
        0.59239193, 0.11971182],
       [0.90190202, 0.88881844, 0.00351585, 0.33014409, 0.41775216,
        1.        , 0.01043228],
       [0.52449568, 0.62040346, 0.58708934, 0.98397695, 0.55365994,
        0.97216138, 0.68657061]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [2]:
import numpy as np

arr = np.random.randint(0, 10, size=(8,10))

min_sum = np.argmin(np.sum(arr, axis=1))

print(arr)

print('индекс:', min_sum)
print('строка:', arr[min_sum])

[[5 8 3 4 0 5 7 0 0 6]
 [6 4 5 0 6 1 2 5 8 1]
 [9 6 8 3 9 1 8 5 0 5]
 [6 2 1 1 7 2 6 8 5 1]
 [8 4 3 7 9 7 9 6 8 3]
 [1 1 1 4 5 0 6 7 3 4]
 [2 5 5 7 1 5 5 1 5 2]
 [6 0 5 8 2 4 8 1 5 0]]
индекс: 5
строка: [1 1 1 4 5 0 6 7 3 4]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [3]:
import numpy as np
import random

database = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, skiprows=1, delimiter=',')
print(database[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [4]:
mean = np.mean(database, axis=0, dtype=int)[1:]
median = np.array(np.median(database, axis=0), dtype=int)[1:]
maximum = np.max(database, axis=0)[1:]
minimum = np.min(database, axis=0)[1:]
print('среднее:', mean)
print('медиана:', median)
print('максимум:', maximum)
print('минимум:', minimum)

среднее: [-21348      9]
медиана: [40  9]
максимум: [2147483647         39]
минимум: [0 1]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [5]:
quint = np.array(np.quantile(database[:, 1], .75, axis=0), dtype=int)
print('значением квантиля:', quint)

значением квантиля: 65


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [6]:
count = np.count_nonzero(database[:, 1] == 0)
print(count)
database[:, 1] = np.where(database[:, 1] == 0, 1, database[:, 1])
count = np.count_nonzero(database[:, 1] == 0)
print(count)

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [7]:
arr = np.unique(database[:, 1:])
print(len(arr))

655


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [8]:
arr = np.unique((database[:, 2]))
print(arr)
print(len(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [9]:
arr = database[database[:, 2] <= 5]
print(arr)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [10]:
maximum = np.max(database[:, 2] / database[:, 1])
print(maximum)

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [11]:
arr = database[database[:, 1].argsort()][::-1]
print(np.mean(arr[:100, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [12]:
print(*random.choices(database, k=10), sep='\n')

[147537     10      3]
[415960      2      5]
[132765     35      7]
[176506     35      7]
[266250     80     13]
[491470      6      6]
[416105      7     10]
[463273     70      9]
[364043     30      9]
[134793     75     12]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [13]:
arr = database[database[:, 2] < mean[-1]]
print(len(arr) / len(database))

0.48217


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [14]:
new_column = (database[:, 1] <= 20) & (database[:, 2] <= 5)
new_database = np.column_stack((database, new_column))
print(new_database)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [15]:
arr = new_database[new_database[:, -1] == 1]
print(len(arr) / len(new_database))

0.09552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [18]:
short_recept = database[database[:, 1] < 10]
standard_recept = database[(database[:, 1] >= 10) & (database[:, 1] < 20)]
long_recept = database[database[:, 1] >= 20]
max_length = min(len(short_recept), len(standard_recept), len(long_recept))
short_recept = short_recept[:max_length]
standard_recept = standard_recept[:max_length]
long_recept = long_recept[:max_length]
print(database[:5])
three_dimensional_array = np.array([short_recept, standard_recept, long_recept])
print("Форма полученного массива:", three_dimensional_array.shape)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]
Форма полученного массива: (3, 7588, 3)
